### PR TITLE
Updated sponsors for fall 2017

### PR DESCRIPTION
**Pull request by dfan**
Title says it all!

### CODE REVIEW

**Review by casey-chow — CHANGES_REQUESTED** [review]
all the logos need to be resized to the size they will be used at, and optimized

@PaliC do you think you can take care of fixing the logos?

**Comment by dfan** [comment]
So I understand the reducing file size part, but not the size. Am I supposed to make a version of the logo for mobile vs. bigger screen? Looking at last year's logos it seemed like they were mostly around 300 pixels long

**Review by zacharyliu — APPROVED** [review]
Eh good enough, we can optimize later if needed

**Comment by zacharyliu** [comment]
David wanted to merge now cause sponsors were asking when it would be up. I agree we should go back and optimize later if we have time though.

**Pull request merged**
